name          'example42-corosync'
version       '3.0.0'
source        'https://github.com/example42/puppet-corosync'
author        'Alessandro Franceschi'
license       'Apache License, Version 2.0'
summary       'This module installs and manages corosync'
description   'This module installs and manages corosync'
project_page  'http://www.example42.com'
